# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=250)),
                ('fruit', models.CharField(choices=[(b'', b'Please choose a fruit'), (b'AP', b'Apple'), (b'BA', b'Banana'), (b'OR', b'Orange'), (b'ST', b'Strawberry')], default=b'', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SqlQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('queueid', models.SmallIntegerField(default=0)),
                ('pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactortoscale.Preference')),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactortoscale.Preference'),
        ),
    ]
